# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recipe/amo_news/summarization.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recipe/amo_news/summarization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#recipe/amo_news/summarization.proto\x12\x0frecipe.amo_news\"c\n\x11\x45valuationRequest\x12\x14\n\x0csolution_str\x18\x01 \x01(\t\x12\x14\n\x0cground_truth\x18\x02 \x01(\t\x12\x0f\n\x07\x61rticle\x18\x03 \x01(\t\x12\x11\n\tdimension\x18\x04 \x01(\t\"#\n\x12\x45valuationResponse\x12\r\n\x05score\x18\x01 \x01(\x01\x32\x84\x01\n\x1eSummarizationEvaluationService\x12\x62\n\x15\x45valuateSummarization\x12\".recipe.amo_news.EvaluationRequest\x1a#.recipe.amo_news.EvaluationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recipe.amo_news.summarization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVALUATIONREQUEST']._serialized_start=56
  _globals['_EVALUATIONREQUEST']._serialized_end=155
  _globals['_EVALUATIONRESPONSE']._serialized_start=157
  _globals['_EVALUATIONRESPONSE']._serialized_end=192
  _globals['_SUMMARIZATIONEVALUATIONSERVICE']._serialized_start=195
  _globals['_SUMMARIZATIONEVALUATIONSERVICE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
