# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recipe/amo_safe/reward.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recipe/amo_safe/reward.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1crecipe/amo_safe/reward.proto\x12\x0frecipe.amo_safe\"0\n\x0cScoreRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\"%\n\rScoreResponse\x12\x14\n\x0creward_score\x18\x01 \x01(\x01\x32`\n\rRewardService\x12O\n\x0c\x43omputeScore\x12\x1d.recipe.amo_safe.ScoreRequest\x1a\x1e.recipe.amo_safe.ScoreResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recipe.amo_safe.reward_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCOREREQUEST']._serialized_start=49
  _globals['_SCOREREQUEST']._serialized_end=97
  _globals['_SCORERESPONSE']._serialized_start=99
  _globals['_SCORERESPONSE']._serialized_end=136
  _globals['_REWARDSERVICE']._serialized_start=138
  _globals['_REWARDSERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
