# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from recipe.amo_safe import reward_pb2 as recipe_dot_amo__safe_dot_reward__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in recipe/amo_safe/reward_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RewardServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeScore = channel.unary_unary(
                '/recipe.amo_safe.RewardService/ComputeScore',
                request_serializer=recipe_dot_amo__safe_dot_reward__pb2.ScoreRequest.SerializeToString,
                response_deserializer=recipe_dot_amo__safe_dot_reward__pb2.ScoreResponse.FromString,
                _registered_method=True)


class RewardServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComputeScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RewardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeScore': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeScore,
                    request_deserializer=recipe_dot_amo__safe_dot_reward__pb2.ScoreRequest.FromString,
                    response_serializer=recipe_dot_amo__safe_dot_reward__pb2.ScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recipe.amo_safe.RewardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recipe.amo_safe.RewardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RewardService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComputeScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recipe.amo_safe.RewardService/ComputeScore',
            recipe_dot_amo__safe_dot_reward__pb2.ScoreRequest.SerializeToString,
            recipe_dot_amo__safe_dot_reward__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
