# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reward.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reward.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creward.proto\x12\x06reward\"0\n\x0cScoreRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\"%\n\rScoreResponse\x12\x14\n\x0creward_score\x18\x01 \x01(\x01\x32N\n\rRewardService\x12=\n\x0c\x43omputeScore\x12\x14.reward.ScoreRequest\x1a\x15.reward.ScoreResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reward_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCOREREQUEST']._serialized_start=24
  _globals['_SCOREREQUEST']._serialized_end=72
  _globals['_SCORERESPONSE']._serialized_start=74
  _globals['_SCORERESPONSE']._serialized_end=111
  _globals['_REWARDSERVICE']._serialized_start=113
  _globals['_REWARDSERVICE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
